# Generated by Django 5.1 on 2024-08-26 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource_contribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESOURCE_REPORT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportComplaint', models.CharField(max_length=100)),
                ('reportDatetime', models.DateTimeField(auto_now_add=True)),
                ('reportResource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_contribution.resource_metadata')),
            ],
        ),
    ]
