# Generated by Django 5.1 on 2024-08-31 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_report', '0002_remove_resource_report_reportresource_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource_report',
            old_name='resourceReport',
            new_name='reportResource',
        ),
    ]
