# Generated by Django 5.1 on 2024-09-01 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_report', '0006_resource_report_reportdoc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_report',
            name='reportDoc',
        ),
    ]
