# Generated by Django 5.1 on 2024-09-01 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_report', '0009_alter_resource_report_reportreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource_report',
            old_name='reportReport',
            new_name='reportResource',
        ),
    ]
