# Generated by Django 5.1 on 2024-09-01 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0003_resource_metadata_file_path'),
        ('resource_report', '0010_rename_reportreport_resource_report_reportresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_report',
            name='reportResource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resource_contribution.resource_metadata'),
        ),
    ]
