# Generated by Django 5.1 on 2024-09-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('openUser', 'Open Access'), ('adminUser', 'Admin'), ('educatorUser', 'Educator'), ('moderatorUser', 'Moderator')], default='openUser', max_length=20),
        ),
    ]
