# Generated by Django 5.1 on 2024-09-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_userprofile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codeTimeStamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
