# Generated by Django 5.1 on 2024-09-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_userprofile_codetimestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='codeTimeStamp',
            new_name='codeTimestamp',
        ),
    ]
