# Generated by Django 5.1 on 2024-08-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_metadata',
            name='contributor',
            field=models.CharField(max_length=100),
        ),
    ]
