# Generated by Django 5.1 on 2024-08-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0002_alter_resource_metadata_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource_metadata',
            name='file_path',
            field=models.CharField(default='No/path', max_length=100),
        ),
    ]
