# Generated by Django 5.0.7 on 2024-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0010_alter_resource_metadata_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_metadata',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
