# Generated by Django 5.1.1 on 2024-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0014_alter_resource_metadata_moderation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource_metadata',
            old_name='file_path',
            new_name='file_path1',
        ),
        migrations.AddField(
            model_name='resource_metadata',
            name='file_path2',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource_metadata',
            name='file_path3',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource_metadata',
            name='file_path4',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AlterField(
            model_name='resource_metadata',
            name='moderation_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
