# Generated by Django 5.1.1 on 2024-10-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0015_rename_file_path_resource_metadata_file_path1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_metadata',
            name='file_type',
        ),
    ]
