# Generated by Django 5.1.2 on 2024-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ANALTICS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_category', models.CharField(blank=True, max_length=100, null=True)),
                ('event_action', models.CharField(blank=True, max_length=100, null=True)),
                ('event_label', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_param', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
