# Generated by Django 5.1.2 on 2024-10-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ANALTICS',
            new_name='ANALYTICS',
        ),
    ]
