# Generated by Django 5.1 on 2024-08-26 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RESOURCE_METADATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('date_contributed', models.DateTimeField(auto_now_add=True)),
                ('resource_rating', models.IntegerField()),
                ('approval_status', models.CharField(max_length=100)),
                ('moderation_comment', models.CharField(max_length=100)),
                ('moderation_date', models.DateTimeField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
