# Generated by Django 5.1 on 2024-09-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0003_resource_metadata_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_metadata',
            name='file_path',
            field=models.FileField(upload_to='resources/'),
        ),
    ]
