# Generated by Django 5.1 on 2024-09-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0007_alter_resource_metadata_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_metadata',
            name='contributor',
            field=models.TextField(),
        ),
    ]
