# Generated by Django 5.1 on 2024-09-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0008_alter_resource_metadata_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_metadata',
            name='contributor',
            field=models.CharField(default=5, max_length=100),
        ),
    ]
