# Generated by Django 5.1 on 2024-09-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0010_alter_resource_metadata_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_metadata',
            name='moderation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
