# Generated by Django 5.0.7 on 2024-09-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0011_alter_resource_metadata_moderation_date'),
        ('resource_contribution', '0012_alter_resource_metadata_resource_rating'),
    ]

    operations = [
    ]
