# Generated by Django 5.1.1 on 2024-09-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0013_merge_20240926_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_metadata',
            name='moderation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
