# Generated by Django 5.1 on 2024-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_report',
            name='reportResource',
        ),
        migrations.AddField(
            model_name='resource_report',
            name='resourceReport',
            field=models.CharField(default='ForeignKeyToResource', max_length=100),
        ),
    ]
