# Generated by Django 5.1 on 2024-09-01 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_contribution', '0003_resource_metadata_file_path'),
        ('resource_report', '0008_remove_resource_report_reportresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_report',
            name='reportReport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resource_contribution.resource_metadata'),
        ),
    ]
