# Generated by Django 5.1.1 on 2024-10-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_analytics', '0002_rename_analtics_analytics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='custom_param',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='event_action',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='event_category',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='event_duration',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='event_label',
        ),
        migrations.AddField(
            model_name='analytics',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analytics',
            name='page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='analytics',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
