name: CI/CD Pipeline

on:
  push:
    branches:
      - DEVELOPMENT
  pull_request:
    branches:
      - DEVELOPMENT


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List entire repository structure
        run: |
          ls -R /home/runner/work/Fullstack-web-application/Fullstack-web-application
    
      - name: Print working directory
        run: |
          pwd  # Print the current working directory
          cd..
          pwd

      - name: List contents of the project directory
        run: |
          ls -la /home/runner/work/Fullstack-web-application/Fullstack-web-application  # List all files

      - name: Find Dockerfile from the correct root
        id: find_dockerfile
        run: |
          DOCKERFILE_PATH=$(find /home/runner/work/Fullstack-web-application/Fullstack-web-application -name Dockerfile -print -quit)  # Adjusted search path
          if [ -z "$DOCKERFILE_PATH" ]; then
            echo "Dockerfile not found"
            exit 1
          fi
          echo "Dockerfile found at: $DOCKERFILE_PATH"
          echo "DOCKERFILE_PATH=$DOCKERFILE_PATH" >> $GITHUB_ENV  # Set the environment variable

      - name: Navigate to Dockerfile directory
        run: |
          DOCKERFILE_DIR=$(dirname "$DOCKERFILE_PATH")  # Get directory of Dockerfile
          cd "$DOCKERFILE_DIR" && pwd  # Change to that directory and print it

      - name: Build Docker image
        run: |
          cd "$DOCKERFILE_DIR"  # Ensure we're in the correct directory
          docker build -t juicebout01/docker-repo:docker-image .

      - name: Push Docker image
        run: |
          docker push juicebout01/docker-repo:docker-image
