name: CI/CD Pipeline

on:
  push:
    branches:
      - DEVELOPMENT
  pull_request:
    branches:
      - DEVELOPMENT


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
      - name: Build Docker image
        run: |
          docker buildx build -t juicebout01/docker-repo:docker-image . -f ProjectBackend/Dockerfile ProjectBackend

      - name: Push Docker image
        run: |
          docker push juicebout01/docker-repo:docker-image
